# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_robstore_wrappers", use_symbols = TRUE, package_name = "robstore")

#' @usage NULL
#' @useDynLib robstore, .registration = TRUE
NULL

#' Create an in-memory store (useful for testing).
#' @return A `Store` object.
#' @export
memory_store <- function() .Call(wrap__memory_store)

#' Create a local filesystem store rooted at `path`.
#'
#' All keys passed to `put`/`get`/`list` are interpreted relative to `path`.
#' The directory must already exist.
#'
#' @param path Absolute or relative path to a directory.
#' @return A `Store` object.
#' @export
local_store <- function(path) .Call(wrap__local_store, path)

#' Create an S3 store for a credentialed bucket.
#'
#' Credentials are resolved from environment variables (AWS_ACCESS_KEY_ID,
#' AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, AWS_REGION) and other standard
#' sources via the object_store crate's AmazonS3Builder.
#'
#' @param bucket Bucket name.
#' @param region AWS region (required for real AWS; use the Pawsey region
#'   string for Pawsey buckets).
#' @param endpoint Optional custom endpoint URL (for S3-compatible services
#'   like Pawsey, MinIO, Backblaze). Pass `NULL` for AWS S3.
#' @param allow_http Allow plain-HTTP endpoints (for local MinIO etc).
#'   Defaults to `FALSE`.
#' @return A `Store` object.
#' @export
s3_store <- function(bucket, region, endpoint, allow_http) .Call(wrap__s3_store, bucket, region, endpoint, allow_http)

#' Create an S3 store with unsigned (anonymous) requests for public buckets.
#'
#' This uses `with_skip_signature(true)` on AmazonS3Builder — equivalent to
#' `AWS_NO_SIGN_REQUEST=YES` in GDAL's /vsis3/, or `anonymous=True` in
#' Python obstore / fsspec.
#'
#' @param bucket Bucket name (e.g. `"sentinel-cogs"`).
#' @param region AWS region (e.g. `"us-west-2"`).
#' @param endpoint Optional custom endpoint URL. Pass `NULL` for AWS S3.
#' @param allow_http Allow plain-HTTP endpoints. Defaults to `FALSE`.
#' @return A `Store` object.
#' @export
s3_store_anonymous <- function(bucket, region, endpoint, allow_http) .Call(wrap__s3_store_anonymous, bucket, region, endpoint, allow_http)

#' Create a GCS store for a credentialed bucket.
#'
#' Credentials are resolved from standard Google Cloud sources:
#'
#' * `GOOGLE_APPLICATION_CREDENTIALS` — path to a service account JSON.
#' * `GOOGLE_SERVICE_ACCOUNT` / `GOOGLE_SERVICE_ACCOUNT_PATH` — alternate
#'   env-var names.
#' * Application Default Credentials (when running on GCE / GKE / etc).
#'
#' @param bucket Bucket name.
#' @return A `Store` object.
#' @export
gcs_store <- function(bucket) .Call(wrap__gcs_store, bucket)

#' Create an anonymous GCS store for a public bucket.
#'
#' Uses unsigned requests — equivalent to Python fsspec's `token='anon'`
#' or GDAL's `GS_NO_SIGN_REQUEST=YES`. Suitable for public buckets like
#' `gcp-public-data-arco-era5`, `gcp-public-data-landsat`, and the
#' Pangeo / Google Research Zarr archives.
#'
#' @param bucket Bucket name (e.g. `"gcp-public-data-arco-era5"`).
#' @return A `Store` object.
#' @export
gcs_store_anonymous <- function(bucket) .Call(wrap__gcs_store_anonymous, bucket)

#' Create an Azure Blob Storage store for a credentialed container.
#'
#' Credentials are resolved from standard Azure sources via
#' `MicrosoftAzureBuilder::from_env()`:
#'
#' * `AZURE_STORAGE_ACCOUNT_NAME` + `AZURE_STORAGE_ACCOUNT_KEY`
#' * `AZURE_STORAGE_SAS_KEY` (SAS token)
#' * `AZURE_STORAGE_CONNECTION_STRING`
#' * Managed identity when running on Azure infrastructure.
#'
#' @param account Storage account name (e.g. `"myaccount"`).
#' @param container Blob container name.
#' @return A `Store` object.
#' @export
azure_store <- function(account, container) .Call(wrap__azure_store, account, container)

#' Create an Azure store authenticated with a SAS token.
#'
#' This is the common access pattern for public Azure datasets such as
#' the Microsoft Planetary Computer, which provides free SAS tokens via
#' an open API:
#'
#' ```
#' https://planetarycomputer.microsoft.com/api/sas/v1/token/{container}
#' ```
#'
#' Unlike S3 and GCS, Azure does not typically permit unsigned
#' anonymous *listing* even on public containers, so a SAS token is
#' required in practice.
#'
#' @param account Storage account name.
#' @param container Blob container name.
#' @param sas_token SAS token string (typically starts with `"sv="`).
#' @return A `Store` object.
#' @export
azure_store_sas <- function(account, container, sas_token) .Call(wrap__azure_store_sas, account, container, sas_token)

#' Create an anonymous Azure store (unsigned).
#'
#' Azure does not generally permit anonymous listing even on "public"
#' containers — you will usually get a 401 `NoAuthenticationInformation`
#' error on `store_list*()` calls. Anonymous *reads* of known blob
#' names may still work depending on the container's public access
#' level. For most real Azure workflows use [`azure_store_sas()`] with
#' a SAS token, or [`azure_store()`] with credentials from environment
#' variables.
#'
#' @param account Storage account name.
#' @param container Blob container name.
#' @return A `Store` object.
#' @export
azure_store_anonymous <- function(account, container) .Call(wrap__azure_store_anonymous, account, container)

#' Write raw bytes to `key` in `store`.
#'
#' @param store A `Store` object.
#' @param key Object key (path) as a string.
#' @param data A raw vector.
#' @return `NULL` invisibly on success.
#' @export
store_put <- function(store, key, data) .Call(wrap__store_put, store, key, data)

#' Read an entire object as a raw vector.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return A raw vector containing the object's bytes.
#' @export
store_get <- function(store, key) .Call(wrap__store_get, store, key)

#' Read a byte range from an object.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @param offset 0-based start offset (double, coerced to u64).
#' @param length Number of bytes to read.
#' @return A raw vector of length `length`.
#' @export
store_get_range <- function(store, key, offset, length) .Call(wrap__store_get_range, store, key, offset, length)

#' Delete an object.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return `NULL` invisibly on success.
#' @export
store_delete <- function(store, key) .Call(wrap__store_delete, store, key)

#' Check whether an object exists.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return `TRUE` or `FALSE`.
#' @export
store_exists <- function(store, key) .Call(wrap__store_exists, store, key)

#' List objects under an optional prefix.
#'
#' Returns a data frame with one row per object: `key` (path), `size`
#' (bytes), `last_modified` (POSIXct, UTC), and `etag`. Pass a `prefix`
#' when listing cloud buckets — most public buckets contain millions of
#' objects and an unbounded list will take a long time and use a lot
#' of memory.
#'
#' To get just the keys, use `df$key` on the result.
#'
#' @param store A `Store` object.
#' @param prefix Optional prefix (string or `NULL`).
#' @return A data frame with columns `key`, `size`, `last_modified`, `etag`.
#' @export
store_list <- function(store, prefix) .Call(wrap__store_list, store, prefix)

#' List objects under many prefixes concurrently.
#'
#' Fires up to `concurrency` independent `list()` calls in parallel and
#' concatenates the results into a single data frame. Useful for
#' hierarchical layouts where you know the top-level directory names
#' a priori (years, MGRS tiles, etc.) and want to parallelise across
#' them instead of walking a single giant paginated listing.
#'
#' @param store A `Store` object.
#' @param prefixes Character vector of prefixes.
#' @param concurrency Maximum number of concurrent list calls.
#' @return A data frame, in no guaranteed row order.
#' @export
store_list_many <- function(store, prefixes, concurrency) .Call(wrap__store_list_many, store, prefixes, concurrency)

#' List one level of the hierarchy under a prefix (delimited listing).
#'
#' Unlike `store_list()` which recursively enumerates every key under the
#' prefix, this returns only the immediate children: the keys that live
#' directly at that level (files) and the "common prefixes" one level
#' deeper (directories). This is the efficient way to explore Zarr
#' stores, large partitioned datasets, or any hierarchical bucket
#' layout — you never accidentally stream millions of chunk keys.
#'
#' Delimiter is always `/`.
#'
#' @param store A `Store` object.
#' @param prefix Optional prefix (string or `NULL`).
#' @return A list with two character vectors:
#'   `keys` (objects at this level) and `common_prefixes` (subdirectories).
#' @export
store_list_delimited <- function(store, prefix) .Call(wrap__store_list_delimited, store, prefix)

#' Copy an object from `from` to `to` within the same store.
#'
#' @param store A `Store` object.
#' @param from Source key.
#' @param to Destination key.
#' @return `NULL` invisibly on success.
#' @export
store_copy <- function(store, from, to) .Call(wrap__store_copy, store, from, to)

#' Read many objects concurrently.
#'
#' Issues up to `concurrency` GET requests at once via the shared tokio
#' runtime. Returns a list of raw vectors, one per input key, in input order.
#' Any failure aborts the whole operation and returns an error.
#'
#' @param store A `Store` object.
#' @param keys Character vector of object keys.
#' @param concurrency Maximum number of concurrent requests.
#' @return A list of raw vectors, length `length(keys)`.
#' @export
store_get_many <- function(store, keys, concurrency) .Call(wrap__store_get_many, store, keys, concurrency)

#' Read many byte ranges concurrently.
#'
#' Each of the three input vectors `keys`, `offsets`, `lengths` must have
#' the same length. Issues up to `concurrency` range-GET requests at once.
#' Returns a list of raw vectors in input order. Ranges can target the
#' same key or different keys — this is the primitive for concurrent
#' COG IFD walks, Zarr chunk reads, Parquet row-group reads.
#'
#' @param store A `Store` object.
#' @param keys Character vector of object keys.
#' @param offsets Numeric vector of 0-based byte offsets (same length).
#' @param lengths Numeric vector of byte lengths (same length).
#' @param concurrency Maximum number of concurrent requests.
#' @return A list of raw vectors.
#' @export
store_get_ranges_many <- function(store, keys, offsets, lengths, concurrency) .Call(wrap__store_get_ranges_many, store, keys, offsets, lengths, concurrency)

Store <- new.env(parent = emptyenv())

Store$describe <- function() .Call(wrap__Store__describe, self)

#' @export
`$.Store` <- function (self, name) { func <- Store[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Store` <- `$.Store`


# nolint end
