# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_robstore_wrappers", use_symbols = TRUE, package_name = "robstore")

#' @usage NULL
#' @useDynLib robstore, .registration = TRUE
NULL

#' Create an in-memory store (useful for testing).
#' @return A `Store` object.
#' @export
memory_store <- function() .Call(wrap__memory_store)

#' Create a local filesystem store rooted at `path`.
#'
#' All keys passed to `put`/`get`/`list` are interpreted relative to `path`.
#' The directory must already exist.
#'
#' @param path Absolute or relative path to a directory.
#' @return A `Store` object.
#' @export
local_store <- function(path) .Call(wrap__local_store, path)

#' Create an S3 store for a credentialed bucket.
#'
#' Credentials are resolved from environment variables (AWS_ACCESS_KEY_ID,
#' AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, AWS_REGION) and other standard
#' sources via the object_store crate's AmazonS3Builder.
#'
#' @param bucket Bucket name.
#' @param region AWS region (required for real AWS; use the Pawsey region
#'   string for Pawsey buckets).
#' @param endpoint Optional custom endpoint URL (for S3-compatible services
#'   like Pawsey, MinIO, Backblaze). Pass `NULL` for AWS S3.
#' @param allow_http Allow plain-HTTP endpoints (for local MinIO etc).
#'   Defaults to `FALSE`.
#' @return A `Store` object.
#' @export
s3_store <- function(bucket, region, endpoint, allow_http) .Call(wrap__s3_store, bucket, region, endpoint, allow_http)

#' Create an S3 store with unsigned (anonymous) requests for public buckets.
#'
#' This uses `with_skip_signature(true)` on AmazonS3Builder — equivalent to
#' `AWS_NO_SIGN_REQUEST=YES` in GDAL's /vsis3/, or `anonymous=True` in
#' Python obstore / fsspec.
#'
#' @param bucket Bucket name (e.g. `"sentinel-cogs"`).
#' @param region AWS region (e.g. `"us-west-2"`).
#' @param endpoint Optional custom endpoint URL. Pass `NULL` for AWS S3.
#' @param allow_http Allow plain-HTTP endpoints. Defaults to `FALSE`.
#' @return A `Store` object.
#' @export
s3_store_anonymous <- function(bucket, region, endpoint, allow_http) .Call(wrap__s3_store_anonymous, bucket, region, endpoint, allow_http)

#' Write raw bytes to `key` in `store`.
#'
#' @param store A `Store` object.
#' @param key Object key (path) as a string.
#' @param data A raw vector.
#' @return `NULL` invisibly on success.
#' @export
store_put <- function(store, key, data) .Call(wrap__store_put, store, key, data)

#' Read an entire object as a raw vector.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return A raw vector containing the object's bytes.
#' @export
store_get <- function(store, key) .Call(wrap__store_get, store, key)

#' Read a byte range from an object.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @param offset 0-based start offset (double, coerced to u64).
#' @param length Number of bytes to read.
#' @return A raw vector of length `length`.
#' @export
store_get_range <- function(store, key, offset, length) .Call(wrap__store_get_range, store, key, offset, length)

#' Delete an object.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return `NULL` invisibly on success.
#' @export
store_delete <- function(store, key) .Call(wrap__store_delete, store, key)

#' Check whether an object exists.
#'
#' @param store A `Store` object.
#' @param key Object key (path).
#' @return `TRUE` or `FALSE`.
#' @export
store_exists <- function(store, key) .Call(wrap__store_exists, store, key)

#' List object keys under an optional prefix.
#'
#' Pass a `prefix` when listing cloud buckets — most public buckets contain
#' millions of objects and an unbounded list will take a long time and use
#' a lot of memory.
#'
#' @param store A `Store` object.
#' @param prefix Optional prefix (string or `NULL`).
#' @return A character vector of object keys.
#' @export
store_list <- function(store, prefix) .Call(wrap__store_list, store, prefix)

#' List object keys under many prefixes concurrently.
#'
#' Fires up to `concurrency` independent `list()` calls in parallel — one
#' per prefix — and flattens the results into a single character vector.
#' Useful for hierarchical layouts where you know the top-level directory
#' names a priori (years, MGRS tiles, etc.) and want to parallelise
#' across them instead of walking a single giant paginated listing.
#'
#' @param store A `Store` object.
#' @param prefixes Character vector of prefixes.
#' @param concurrency Maximum number of concurrent list calls.
#' @return A character vector of all keys across all prefixes, in no
#'   guaranteed order.
#' @export
store_list_many <- function(store, prefixes, concurrency) .Call(wrap__store_list_many, store, prefixes, concurrency)

#' Copy an object from `from` to `to` within the same store.
#'
#' @param store A `Store` object.
#' @param from Source key.
#' @param to Destination key.
#' @return `NULL` invisibly on success.
#' @export
store_copy <- function(store, from, to) .Call(wrap__store_copy, store, from, to)

#' Read many objects concurrently.
#'
#' Issues up to `concurrency` GET requests at once via the shared tokio
#' runtime. Returns a list of raw vectors, one per input key, in input order.
#' Any failure aborts the whole operation and returns an error.
#'
#' @param store A `Store` object.
#' @param keys Character vector of object keys.
#' @param concurrency Maximum number of concurrent requests.
#' @return A list of raw vectors, length `length(keys)`.
#' @export
store_get_many <- function(store, keys, concurrency) .Call(wrap__store_get_many, store, keys, concurrency)

#' Read many byte ranges concurrently.
#'
#' Each of the three input vectors `keys`, `offsets`, `lengths` must have
#' the same length. Issues up to `concurrency` range-GET requests at once.
#' Returns a list of raw vectors in input order. Ranges can target the
#' same key or different keys — this is the primitive for concurrent
#' COG IFD walks, Zarr chunk reads, Parquet row-group reads.
#'
#' @param store A `Store` object.
#' @param keys Character vector of object keys.
#' @param offsets Numeric vector of 0-based byte offsets (same length).
#' @param lengths Numeric vector of byte lengths (same length).
#' @param concurrency Maximum number of concurrent requests.
#' @return A list of raw vectors.
#' @export
store_get_ranges_many <- function(store, keys, offsets, lengths, concurrency) .Call(wrap__store_get_ranges_many, store, keys, offsets, lengths, concurrency)

Store <- new.env(parent = emptyenv())

Store$describe <- function() .Call(wrap__Store__describe, self)

#' @export
`$.Store` <- function (self, name) { func <- Store[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Store` <- `$.Store`


# nolint end
